-- AJAG Golf — catálogo de campos de golf (club + recorrido), para que el
-- admin pueda buscar/seleccionar el campo al crear un torneo en vez de
-- escribirlo a mano cada vez. Sembrado inicialmente con los clubes y
-- recorridos de Andalucía (nombre y recorrido únicamente, sin tees ni
-- valoraciones vc/vs).

create table campos_golf (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  recorrido text not null,
  created_at timestamptz not null default now(),
  unique (nombre, recorrido)
);

alter table campos_golf enable row level security;

create policy "campos_golf_select_publico"
  on campos_golf for select
  using (true);

create policy "campos_golf_insert_admin"
  on campos_golf for insert
  with check (is_admin());

alter table torneos add column recorrido text;

insert into campos_golf (nombre, recorrido) values
  ('Real Club de Campo de Malaga', 'CAMPO DE MALAGA  AMARILLO-BLANCO PROVISIONAL'),
  ('Real Club de Campo de Malaga', 'CAMPO DE MALAGA  H 4 Y 5'),
  ('Real Club de Campo de Malaga', 'CAMPO DE MALAGA - Amarillo + Blanco'),
  ('Real Club Pineda de Sevilla', 'RCG PINEDA   A+A'),
  ('Real Club Pineda de Sevilla', 'RC PINEDA - RC Pineda'),
  ('Real Club Pineda de Sevilla', 'PINEDA CTO ESPAÑA SENIOR MASC 2026'),
  ('Real Club de Golf Sotogrande', 'RC SOTOGRANDE - Recorrido 2'),
  ('Real Club de Golf Sotogrande', 'RC SOTOGRANDE - Corto'),
  ('Real Club de Golf Sotogrande', 'RC SOTOGRANDE - Recorrido 1'),
  ('Real Club El Candado', 'REAL EL CANDADO'),
  ('Real Club de Golf Vista Hermosa', 'VISTA HERMOSA - Vista Hermosa'),
  ('Real Club de Campo de Cordoba', 'CORDOBA C.DE CAMPO - Cordoba'),
  ('Club de Golf Bellavista', 'BELLAVISTA - Pequecircuito'),
  ('Club de Golf Bellavista', 'BELLAVISTA - Bellavista'),
  ('Real Club de Golf Las Brisas', 'LAS BRISAS - Las Brisas'),
  ('Club de Golf Pozoblanco', 'POZOBLANCO - Pozoblanco'),
  ('Club de Golf La Cañada', 'LA CAÑADA - La Cañada'),
  ('Club de Golf La Cañada', 'LA CAÑADA - Niños'),
  ('Club de Golf La Cañada', 'LA CAÑADA - Provisional obras H17'),
  ('Real Club Valderrama', 'REAL CLUB VALDERRAMA - Valderrama'),
  ('Real Club Valderrama', 'REAL CLUB VALDERRAMA  - Pares 3'),
  ('Real Guadalhorce Club de Golf', 'GUADALHORCE - Pares 3'),
  ('Real Guadalhorce Club de Golf', 'REAL GUADALHORCE'),
  ('San Roque Club', 'SAN ROQUE - Old Course'),
  ('Real Novo Sancti Petri Golf Club', 'R. NOVO SANCTI PETRI - Mar + Centro'),
  ('Real Novo Sancti Petri Golf Club', 'R. NOVO SANCTI PETRI - Rec A, Mar y Pinos'),
  ('Real Novo Sancti Petri Golf Club', 'R. NOVO SANCTI PETRI - Rec B, Centro'),
  ('Club de Campo La Zagaleta', 'LA ZAGALETA - Los Barrancos'),
  ('Club de Campo La Zagaleta', 'LA ZAGALETA - Old Course'),
  ('Alhaurín Golf Hotel & Resort', 'ALHAURIN - Alhaurin'),
  ('La Envia Golf', 'LA ENVIA - Pequecircuito'),
  ('La Envia Golf', 'LA ENVIA - La Envía'),
  ('Higuerón Marbella Golf Resort', 'MARBELLA GOLF'),
  ('Costa Ballena Ocean Golf Club', 'COSTA BALLENA - Pares 3'),
  ('Costa Ballena Ocean Golf Club', 'COSTA BALLENA - Olivos + Palmeras'),
  ('Costa Ballena Ocean Golf Club', 'COSTA BALLENA - Palmeras + Ficus'),
  ('Costa Ballena Ocean Golf Club', 'COSTA BALLENA - Ficus + Olivos'),
  ('Costa Ballena Ocean Golf Club', 'COSTA BALLENA  FICUS + PALMERAS'),
  ('Campo de Golf Dehesa Montenmedio', 'MONTENMEDIO'),
  ('Montecastillo Barceló Golf Club', 'MONTECASTILLO'),
  ('Montecastillo Barceló Golf Club', 'MONTECASTILLO   EBTC 2026'),
  ('Club Marina Golf-Mojacar', 'MARINA GOLF - Marina Golf'),
  ('Greenlife Golf Club S.l.', 'GREENLIFE GOLF - Greenlife'),
  ('Parque Deportivo La Garza', 'LA GARZA - La Garza'),
  ('Parque Deportivo La Garza', 'LA GARZA - Largo'),
  ('Parque Deportivo La Garza', 'LA GARZA - Corto'),
  ('Parque Deportivo La Garza', 'LA GARZA - Combo'),
  ('Fairplay Golf & Spa Resort', 'FAIRPLAY GOLF & SPA RESORT - Fairplay Golf'),
  ('Villa Padierna Golf Club', 'VILLAPADIERNA GOLF - Tramores'),
  ('Villa Padierna Golf Club', 'VILLAPADIERNA GOLF - Alferini'),
  ('Villa Padierna Golf Club', 'VILLAPADIERNA GOLF - Flamingos'),
  ('Real Club de Golf Guadalmina', 'RCG GUADALMINA - Sur'),
  ('Real Club de Golf Guadalmina', 'RCG GUADALMINA NORTE A + A'),
  ('Real Club de Golf Guadalmina', 'RCG GUADALMINA - Norte'),
  ('Golf Río Real', 'RIO REAL - Río Real'),
  ('Golf Río Real', 'RÍO REAL - Par 68'),
  ('Golf Río Real', 'RÍO REAL Par 71'),
  ('Atalaya Golf & Country Club', 'ATALAYA PARK - New Course'),
  ('Atalaya Golf & Country Club', 'ATALAYA PARK - Old Course'),
  ('Los Naranjos Golf Club', 'LOS NARANJOS'),
  ('El Paraíso Golf Club', 'EL PARAISO - El Paraiso Golf'),
  ('El Paraíso Golf Club', 'EL PARAÍSO cambio orden hoyos'),
  ('Aloha Golf', 'ALOHA - Aloha'),
  ('Baviera Golf', 'BAVIERA GOLF - Baviera'),
  ('Baviera Golf', 'BAVIERA GOLF - Pequecircuito'),
  ('Golf Almerimar', 'ALMERIMAR - Almerimar 18 Hoyos A+B'),
  ('Golf Almerimar', 'ALMERIMAR - C+C'),
  ('Golf Almerimar', 'ALMERIMAR - Rojo+Azul'),
  ('Golf Almerimar', 'ALMERIMAR - Blanco+Rojo'),
  ('Golf Almerimar', 'ALMERIMAR - Azul+Blanco'),
  ('Golf Torrequebrada', 'TORREQUEBRADA GOLF - Torrequebrada Golf'),
  ('Mijas Golf Internacional', 'GOLF MIJAS - Los Olivos'),
  ('Mijas Golf Internacional', 'GOLF MIJAS - Los Lagos'),
  ('Club de Golf Playa Serena', 'PLAYA SERENA - Playa Serena'),
  ('Club de Golf Playa Serena', 'PLAYA SERENA - Pequecircuito'),
  ('Desert Springs Golf Club', 'DESERT SPRINGS- Indiana'),
  ('Desert Springs Golf Club', 'DESERT SPRINGS - Alternativo'),
  ('La Duquesa Golf & Country Club', 'LA DUQUESA'),
  ('Granada Club de Golf', 'GRANADA C.GOLF - Pequecircuito'),
  ('Granada Club de Golf', 'GRANADA C.GOLF - Granada'),
  ('Club de Golf Campano', 'GOLF CAMPANO - Golf Campano'),
  ('Los Moriscos Club de Golf', 'LOS MORISCOS - Pequecircuito'),
  ('Los Moriscos Club de Golf', 'LOS MORISCOS - Los Moriscos Golf'),
  ('Los Moriscos Club de Golf', 'LOS MORISCOS PROV. H10'),
  ('Cabopino Golf Marbella', 'CABOPINO - Cabopino'),
  ('La Quinta Golf & Country Club', 'LA QUINTA - San Pedro+Ronda'),
  ('La Quinta Golf & Country Club', 'LA QUINTA - Ronda+Guadaiza'),
  ('La Quinta Golf & Country Club', 'LA QUINTA - San Pedro+Guadaiza'),
  ('Club de Campo Las Minas Golf', 'LAS MINAS - Pequecircuito'),
  ('Club de Campo Las Minas Golf', 'LAS MINAS - Las Minas'),
  ('Santa Clara Golf', 'SANTA CLARA MARBELLA'),
  ('Club de Golf La Siesta', 'GOLF LA SIESTA - Golf La Siesta'),
  ('Club Deportivo Añoreta Golf', 'AÑORETA GOLF - 9 hoyos'),
  ('Club Deportivo Añoreta Golf', 'AÑORETA GOLF - Añoreta Golf'),
  ('Miraflores Golf', 'MIRAFLORES CLUB GOLF'),
  ('Estepona Golf', 'ESTEPONA GOLF'),
  ('Golf Nuevo Portil', 'NUEVO PORTIL'),
  ('La Cala Resort', 'LA CALA - Campo America'),
  ('La Cala Resort', 'LA CALA - Campo Asia'),
  ('La Cala Resort', 'LA CALA - Campo Europa'),
  ('La Cala Resort', 'LA CALA  PARES 3'),
  ('Lauro Golf', 'LAURO - C+C'),
  ('Lauro Golf', 'LAURO - A+B'),
  ('Lauro Golf', 'LAURO - B+C'),
  ('Lauro Golf', 'LAURO - C+A'),
  ('Alcaidesa Links Golf Resort', 'LA HACIENDA - Heathland'),
  ('Alcaidesa Links Golf Resort', 'LA HACIENDA - LINKS'),
  ('Real Club Sevilla Golf', 'RCG SEVILLA'),
  ('Santa María Golf & Country Club', 'SANTA MARIA GOLF'),
  ('Los Arqueros Golf & Country Club', 'ARQUEROS GOLF - Par 72'),
  ('Los Arqueros Golf & Country Club', 'ARQUEROS GOLF - Los Arqueros'),
  ('Banus Executive Golf', 'BANUS EXECUTIVE - Banus Executive'),
  ('Islantilla Golf Resort, S.l', 'ISLANTILLA - Azul+Amarillo'),
  ('Islantilla Golf Resort, S.l', 'ISLANTILLA - Amarillo+Verde'),
  ('Islantilla Golf Resort, S.l', 'ISLANTILLA - Verde+Azul'),
  ('Club de Golf Corta Atalaya', 'CORTA ATALAYA'),
  ('Club Zaudín Golf', 'ZAUDIN - Zaudín'),
  ('Isla Canela Old Course', 'ISLA CANELA - Pequecircuito'),
  ('Isla Canela Old Course', 'ISLA CANELA OLD COURSE - Isla Canela'),
  ('The Alto Club Sotogrande', 'ALMENARA - Pinos+Lagos'),
  ('The Alto Club Sotogrande', 'ALMENARA  EXECUTIVE'),
  ('The Alto Club Sotogrande', 'ALMENARA   PAR 3'),
  ('Valle Del Este Hotel Golf Spa', 'VALLE DEL ESTE - Valle Del Este Golf'),
  ('Golf El Rompido', 'ROMPIDO GOLF - Sur'),
  ('Golf El Rompido', 'ROMPIDO GOLF - Norte'),
  ('Antequera Golf', 'ANTEQUERA GOLF'),
  ('La Noria Golf And Resort', 'LA NORIA'),
  ('La Luna de Doñana. Club de Campo y Golf', 'LA LUNA DE DOÑANA'),
  ('El Campanario Ocio y Turismo', 'EL CAMPANARIO - Pares 3'),
  ('Club de Golf La Reserva de Sotogrande', 'LA RESERVA - La Reserva'),
  ('Sherry Golf Jerez', 'SHERRY GOLF JEREZ - Pares 3'),
  ('Sherry Golf Jerez', 'SHERRY GOLF JEREZ - Sherry Golf'),
  ('Magna Marbella Golf', 'MAGNA MARBELLA - Magna Marbella'),
  ('Alborán Golf', 'ALBORÁN GOLF - Alborán'),
  ('Parador Málaga Del Golf', 'PARADOR MALAGA  AMARILLO-BLANCO PROVISIONAL'),
  ('Parador Málaga Del Golf', 'PARADOR MALAGA  H 4 Y 5'),
  ('Parador Málaga Del Golf', 'PARADOR MALAGA - Amarillo+Blanco'),
  ('Doña Julia Golf Club', 'DOÑA JULIA GOLF'),
  ('Villa Nueva Golf & Croquet', 'VILLANUEVA GOLF - Villanueva Golf'),
  ('El Chaparral Golf Club', 'EL CHAPARRAL - El Chaparral'),
  ('El Chaparral Golf Club', 'CHAPARRAL - B+B'),
  ('La Resina Golf & Country Club', 'LA RESINA'),
  ('Calanova Golf Club', 'CALANOVA GOLF'),
  ('Arcos Golf', 'ARCOS GARDENS'),
  ('Santa Clara Golf Club Granada', 'SANTA CLARA GRANADA - Santa Clara Granada'),
  ('Finca Cortesin Golf Club', 'EL CORTESIN'),
  ('Rota Club de Golf', 'ROTA CLUB DE GOLF'),
  ('Sancti Petri Hills Golf', 'SANCTI PETRI HILLS - Sancti Petri Hills'),
  ('Casares Costa Golf', 'CASARES COSTA  GOLF'),
  ('Club Hato Verde', 'GOLF HATO VERDE - Pequecircuito'),
  ('Club Hato Verde', 'GOLF HATO VERDE - Hato Verde'),
  ('Aguilon Golf', 'AGUILON GOLF - Aguilón Golf'),
  ('Escuela Pública La Cartuja', 'ESC LA CARTUJA - La Cartuja'),
  ('Valle Romano Golf & Resort', 'VALLE ROMANO - Valle Romano'),
  ('Valle Romano Golf & Resort', 'VALLE ROMANO - B+A'),
  ('La Monacilla Golf Club', 'LA MONACILLA - La Monacilla'),
  ('La Estancia Golf', 'LA ESTANCIA'),
  ('Chiclana Family Golf Park', 'CHICLANA FAMILY - Pares 3'),
  ('Marbella Club And Golf Resort', 'MARBELLA CLUB'),
  ('El Higueral', 'EL HIGUERAL'),
  ('Azata Golf', 'AZATA - Azata'),
  ('Isla Canela Links', 'ISLA CANELA  LINKS'),
  ('SAN ROQUE GOLF & RESORT', 'SAN ROQUE NEW')
on conflict (nombre, recorrido) do nothing;
